ci: adicionando pipeline de docker
mentoriaiac/cicd_centralizado pull request #11
Opened 2022-05-21 01:40 UTC by midgardhero

Trabalho inicial na criação de pipeline de docker, com passos para o
build da imagem e scan lint do dockerfile.

Co-authored-by: Luiz Aoqui <lgfa29@gmail.com>
Co-authored-by: Edemir Toldo <edemirtoldo@gmail.com>
Co-authored-by: Danilo F Rocha <snifbr@gmail.com>
Co-authored-by: Acássio Moura <maestro.etmaxx@gmail.com>
Co-authored-by: Murillo Gomes <mganalistati@gmail.com>
Co-authored-by: Keven S. Lopes <l40838038+stephan-lopes@users.noreply.github.com>
Co-authored-by: Marcone M. Melo <marcone.tzimisce@gmail.com>
Co-authored-by: Vinicius Silva <bl4cktux89@gmail.com>
Co-authored-by: Gerlucio Moura <gerluciomoura@gmail.com>

- [x] Garanta que seu **topic/feature/bugfix branch** tenha uma branch nomeada e não a sua branch main esteja no PR
- [x] Dê um titulo que expresse o objetivo do PR
- [x] Associe seu PR a uma Issue criada no repositósito. Caso seja uma correção de linguagem ou pequenas correções, não é necessário
- [x] Descreva o objetivo do PR
- [x] Inclua links relevantes para a sua modificação/sugestão/correção
- [x] Descreva um passo-a-passo para testar o seu PR

## Issue

closes #4 

## Objetivo

Criação de pipeline reutilizável para buildar docker

## Referências

https://github.com/mentoriaiac/documentos/blob/main/rfcs/RFC-002.md

## Como testar

Repositório de exemplo de testes:
https://github.com/midgardhero/teste-pipeline-docker

2022-06-11 15:28 UTC, gomex requested changes
O PR está MUITO BOM mesmo. Parabéns a quem trabalhou nisso. Vcs devem se orgulhar o trabalho entregue. De verdade.

So colocar um fim de linha em branco e estará ok.

Outra coisa é criar um arquivo de documentação para uso desse pipeline, pode seguir esse exemplo aqui: https://github.com/mentoriaiac/cicd_centralizado/blob/main/docs/ansible_valida_role.md

Inclusive vc pode usar os elementos que colocou no seu repo de teste: https://github.com/midgardhero/teste-pipeline-docker/blob/main/.github/workflows/ci.yaml

2022-06-11 15:28 UTC, gomex commented on .github/workflows/docker_build.yaml
> +          docker image push ${{inputs.tag}}
Coloca uma linha em branco no final?

2022-06-11 22:47 UTC, lgfa29 requested changes

2022-06-11 22:47 UTC, lgfa29 commented on .github/workflows/docker_build.yaml
> +          echo """${{inputs.trivy_ignore}}""" > .trivyignore
Vamos testar se dá para usar a pipeline sem precisar desses passos. Eu acho que se o repositório que estiver chamando a pipeline já tiver eles esses steps já vão ler automaticamente.

2022-06-12 15:32 UTC, gomex commented on .github/workflows/docker_build.yaml
> +          echo """${{inputs.trivy_ignore}}""" > .trivyignore
Verdade, vale a pena testar e tirar essas etapas que podem quebrar o processo no futuro por uma mudança no comportamento do trivy ;)

2022-06-28 23:41 UTC, midgardhero commented on .github/workflows/docker_build.yaml
> +          docker image push ${{inputs.tag}}
linha adicionada

2022-06-29 23:43 UTC, LeandroFischer commented on .github/workflows/docker_build.yaml
> +          echo """${{inputs.trivy_ignore}}""" > .trivyignore
Foram removidas as linhas que citaram e o input que foi criado para esses steps, testamos a execução da action no novo formato, no repositório de testes, executou normalmente.

2022-07-01 00:14 UTC, gomex requested changes
Ta ficando muito bom, mas tenho algumas sugestões pra deixar melhor ainda.

2022-07-01 00:14 UTC, gomex commented on .github/workflows/docker_build.yaml
> +        type: string
Eu estava pensando aqui, e se esse input só cuidasse do nome da imagem e a parte da tag fosse cuidada pelo pipeline centralizado?

O build seria feito com base no commit atual e o release com base na tag ;) 

**Pegar o commit atual:**
```
$(git rev-parse --short "$GITHUB_SHA")
```

**Pegar a tag da release:**
```
${GITHUB_REF#refs/*/}
```
Eu vou colocar a sugestão lá embaixo, mas precisa testar, pois faz tempo que fiz isso e a documentação não estava clara nesse ponto.

2022-07-01 00:14 UTC, gomex commented on .github/workflows/docker_build.yaml
> +name: "Docker Build Scan"
Por que o nome é Build Scan? Não seria melhor Build Tag Push? Scan eu acho que é parte do build, não?

2022-07-01 00:14 UTC, gomex commented on .github/workflows/docker_build.yaml
> +          docker image push ${{inputs.tag}}
```suggestion
      - name: Build
        run: |
          docker image build --tag ${{inputs.image}}:$(git rev-parse --short "$GITHUB_SHA") .
      - name: Rodar Scan de vulnerabilidade Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{inputs.image}}:$(git rev-parse --short "$GITHUB_SHA")
          format: 'table'
          exit-code: '1'
          severity: ${{inputs.trivy_severity}}
      - name: push da imagem
        if: ${{inputs.push_image}}
        run: |
          docker login --username ${{secrets.docker_user}} --password ${{secrets.docker_password}}
          docker tag ${{inputs.image}}:$(git rev-parse --short "$GITHUB_SHA")
          docker image push ${{inputs.image}}:${GITHUB_REF#refs/*/}
```

2022-07-01 00:14 UTC, gomex commented on .github/workflows/docker_build.yaml
> +        description: "tag da imagem docker"
```suggestion
      image:
        description: "Nome da imagem docker"
```

2022-07-01 00:14 UTC, gomex commented on .github/workflows/docker_build.yaml
> +        type: string
Não ficou claro que input seria esse. Isso é pra mudar o arquivo ou passar parâmetros? Ele não ta mais sendo usado dentro do pipeline centralizado :)

2022-07-01 02:01 UTC, midgardhero commented on .github/workflows/docker_build.yaml
> +name: "Docker Build Scan"
Concordo, acho que pode ser melhor nomeado dessa forma mesmo

2022-07-01 12:40 UTC, lgfa29 commented on .github/workflows/docker_build.yaml
> +        type: string
Inicialmente eu pensei que isso seria feita na chamada da pipeline, tipo assim:

```yaml
jobs:
  docker:
    uses: "mentoriaiac/cicd_centralizado/.github/workflows/docker_build.yaml"
    with:
      tag: user/image:${{ github.sha }}
```

Mas como é um padrão que eu acho que vai ser comum em todos os projetos, faz sentido oferecer essa lógica de forma automática.

A minha única sugestão a mais seria de manter a variável `tag` mas deixar como opcional, dessa forma tem um jeito de forçar um valor se for preciso. Aí a precedência dos valores seria:

1. Input `tag`
2. Nome da tag git
3. SHA do commit

Uma outra coisa a pensar é em relação à tag `latest`. Talvez seria legal ter uma flag para controlar se ela é atualizada também? E aí o padrão pode ser `true` já que imagino que esse seja o caso mais comum.

2022-07-01 12:46 UTC, lgfa29 commented on .github/workflows/docker_build.yaml
> +        type: string
Ah é, e para pegar os valores tem umas [variáveis de ambiente](https://docs.github.com/pt/actions/learn-github-actions/environment-variables#default-environment-variables) disponíveis.

No nosso caso teria que ver se  `GITHUB_REF_TYPE` é `tag` e aí usar `GITHUB_REF_NAME` ou `GITHUB_SHA`.

2022-07-01 12:49 UTC, lgfa29 commented on .github/workflows/docker_build.yaml
> +        type: string
É, pode ser removido ou passado para a action do Trivy como o [input `trivyignores`](https://github.com/aquasecurity/trivy-action#inputs) se o repositório tiver mais de um, ou usar um valor não padrão. 

Mas acho que pode só retirar mesmo, `.trivyignore` é provavelmente o caminho mais utilizado mesmo.

2022-07-01 13:06 UTC, lgfa29 commented on .github/workflows/docker_build.yaml
> +      - name: push da imagem
```suggestion
      - name: Push da imagem
```

2022-07-01 13:06 UTC, lgfa29 commented on .github/workflows/docker_build.yaml
> +name: "Docker Build Scan"
Também atualizar o [nome do job](https://github.com/mentoriaiac/cicd_centralizado/blob/f9ae99ca2268fffa7396f35e159dc1a1a6382790/.github/workflows/docker_build.yaml#L44).

2022-07-01 13:06 UTC, lgfa29 commented on docs/docker_build.md
> +Github Actions para ser reutilizado nos projetos de Imagem Docker. Faz a processo de Build, lint Scan e Push da imagem.
```suggestion
Github Actions para ser reutilizado nos projetos de Imagem Docker. Faz a processo de build, lint, scan e push da imagem. 

```

2022-07-01 13:06 UTC, lgfa29 commented on docs/docker_build.md
> +| tag | tag da imagem docker | sim | N/A | string |
```suggestion
| tag | tag da imagem docker | sim | N/A | string |
| os_version | Versão do sistema operacional | não | ubuntu-20.04 | string |
```

Geralmente é sempre bom começar pelos inputs mandatórios.

2022-07-01 13:06 UTC, lgfa29 commented on docs/docker_build.md
> +| push_image | escolha se deve ser feito push da imagem | não | não | boolean |
```suggestion
| `os_version` | Versão do sistema operacional | não | `ubuntu-20.04` | string |
| `tag` | tag da imagem docker | sim | N/A | string |
| `hadolint_version` | versão do hadolint | não | `v2.9.2` | string |
| `trivy_ignore` | arquivo .trivyignore | não | `.trivyignore` | string |
| `trivy_severity` | nível de severidade para scan | não | `CRITICAL,HIGH` | string |
| `push_image` | escolha se deve ser feito push da imagem | não | `false` | boolean |

```

2022-07-01 13:06 UTC, lgfa29 commented on docs/docker_build.md
> +    uses: "mentoriaiac/cicd_centralizado/.github/workflows/docker_build.yaml@v1"
@gomex agora que tá começcando a ter mais pipelines diferentes seria bom definir como vai acontecer o versionamento. 

Eu acho que o a gente tinha discutido é usar o tipo da pipeline na versão né, aí nesse caso ficaria algo assim?

```suggestion
    uses: "mentoriaiac/cicd_centralizado/.github/workflows/docker_build.yaml@docker/v1"
```

2022-07-01 13:06 UTC, lgfa29 commented on docs/docker_build.md
> +        CVE-2020-36518
```suggestion
```

2022-07-06 01:35 UTC, midgardhero commented on .github/workflows/docker_build.yaml
> +name: "Docker Build Scan"
nome alterado para Docker Build Tag Push

2022-07-06 01:47 UTC, midgardhero commented on .github/workflows/docker_build.yaml
> +        type: string
Removido o input

2022-07-10 15:09 UTC, gomex requested changes
Está ficando perfeito. Faltam apenas alguns ajustes.

2022-07-10 15:09 UTC, gomex commented on .github/workflows/docker_build.yaml
> +          docker tag ${{inputs.image}}:$(git rev-parse --short "$GITHUB_SHA")
```suggestion
          docker tag ${{inputs.image}}:$(git rev-parse --short "$GITHUB_SHA") ${{inputs.image}}:${GITHUB_REF#refs/*/}
```

2022-07-10 15:09 UTC, gomex commented on docs/docker_build.md
> +      tag: USUARIO/REPOSITORIO_DOCKER:TAG
```suggestion
      image: USUARIO/REPOSITORIO_DOCKER

```

2022-07-10 15:11 UTC, gomex requested changes

2022-07-10 15:11 UTC, gomex commented on docs/docker_build.md
> +| tag | tag da imagem docker | sim | N/A | string |
```suggestion
| image | nome da imagem docker | sim | N/A | string |

```

2022-07-10 15:31 UTC, gomex commented
Eu testei e está falhando no trivy: https://github.com/gomex/docker-packer-ansible/runs/7271542733?check_suite_focus=true

2022-07-24 03:39 UTC, merged