Feat/ reuso workflow modulos terraform
mentoriaiac/cicd_centralizado pull request #3
Opened 2022-04-13 23:57 UTC by EzzioMoreira

# Titulo

Cria github actions reutilizavel para modules terraform de acordo com a issue
`Criação do workflow reutilizável para teste de módulos Terraform #1`

- [ ] Garanta que seu **topic/feature/bugfix branch** tenha uma branch nomeada e não a sua branch main esteja no PR
- [x] Dê um titulo que expresse o objetivo do PR
- [ ] Associe seu PR a uma Issue criada no repositósito. Caso seja uma correção de linguagem ou pequenas correções, não é necessário
- [ x] Descreva o objetivo do PR
- [ ] Inclua links relevantes para a sua modificação/sugestão/correção
- [ ] Descreva um passo-a-passo para testar o seu PR

## Issue
https://github.com/mentoriaiac/cicd_centralizado/issues/1

## Objetivo
Cria um workflow que será reutilizado nos pipilie de CI dos modulos terraform. 

## Referências

https://github.com/mentoriaiac/documentos/blob/main/rfcs/RFC-002.md

## Como testar
Criar um repositorio criar um workflow github actions utilizando o seguinte código: 
```yaml
name: "Terraform Valida Modulo"

on:
  push:
    - main
  pull_request:

jobs:
  terraform:
      uses: "https://github.com/mentoriaiac/cicd_centralizado@v1"
      with: 
        tf_version: "1.0.0"
        os_version: "ubuntu-20.04"
      secrets:
        token: ${{ secrets.TOKEN }}
```

2022-04-14 11:11 UTC, gomex requested changes
Está ficando massa! Só tem dois detalhes pra pontuar.

2022-04-14 11:11 UTC, gomex commented on .github/workflows/terraform_valida_modulo.yaml
> +    continue-on-error: true
Por que essa flag é true? isso afetará todo job, né? O ideal é que quebre mesmo, não?

2022-04-14 11:11 UTC, gomex commented on docs/terraform_valida_modulo copy.md
> +      uses: "https://github.com/mentoriaiac/cicd_centralizado@v1"
Precisa do path inteiro, não?

2022-04-14 11:12 UTC, gomex requested changes

2022-04-14 11:12 UTC, gomex commented on docs/terraform_valida_modulo copy.md
> +# Terraform Valida Módulo
O nome do arquivo está estranho

2022-04-23 20:57 UTC, EzzioMoreira commented on .github/workflows/terraform_valida_modulo.yaml
> +    continue-on-error: true
@gomex eu só fiz um copiar e colar, não faço ideia porque está com essa opção e na documentação da actions `https://github.com/hashicorp/setup-terraform` não deixa claro a usabilidade dessa opção. 
Eu removi essa opção `continue-on-error` logo em seguida fiz um teste e o pipeline funcionou normalmente. 
Obrigado pela observação. 
![image](https://user-images.githubusercontent.com/18507157/164945709-4e6e5a3c-9c72-4578-89ab-92522c859578.png)

2022-04-23 21:01 UTC, EzzioMoreira commented on docs/terraform_valida_modulo copy.md
> +      uses: "https://github.com/mentoriaiac/cicd_centralizado@v1"
Sim, vocẽ tem razão.

2022-04-23 21:04 UTC, EzzioMoreira commented on docs/terraform_valida_modulo copy.md
> +# Terraform Valida Módulo
Corrigindo.

2022-04-24 14:05 UTC, gomex approved these changes
Muito bom! Parabéns!

2022-04-24 14:06 UTC, merged